// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNHj4xAYHfRUnTYzdOBJZilXliXqZCFg',
    appId: '1:776235796714:web:ac6b0007ccb1b23549af93',
    messagingSenderId: '776235796714',
    projectId: 'chatapp-9ed68',
    authDomain: 'chatapp-9ed68.firebaseapp.com',
    storageBucket: 'chatapp-9ed68.appspot.com',
    measurementId: 'G-NJDY8T7KZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA46y_s5s0crOjkzVPc-_iR5KmAULEC-AA',
    appId: '1:776235796714:android:fe713befdf9b845349af93',
    messagingSenderId: '776235796714',
    projectId: 'chatapp-9ed68',
    storageBucket: 'chatapp-9ed68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrr_EIpnlHlyqOkbmejT_43I8xdOsyzw',
    appId: '1:776235796714:ios:45436472e6ef18b849af93',
    messagingSenderId: '776235796714',
    projectId: 'chatapp-9ed68',
    storageBucket: 'chatapp-9ed68.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrr_EIpnlHlyqOkbmejT_43I8xdOsyzw',
    appId: '1:776235796714:ios:57a750cbc24a5fc149af93',
    messagingSenderId: '776235796714',
    projectId: 'chatapp-9ed68',
    storageBucket: 'chatapp-9ed68.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
